### ISSUE TITLE
DCMC - Firmware

### ISSUE THREAD

**Issue by OrsoEric** [OrsoEric/OrangeBot-motor-controller-v2#5]
Firmware for the DCMC (DC Motor Controller)

Breadboard Tests  
- [ ] Longan Nano LCD
- [ ] Longan Nano Task Scheduler
- [ ] Longan nano ADC
- [ ] VNH7040 Open Loop PWM Ramp
- [ ] IG32-05 Encoder acquisition
- [ ] VNH7040 Closed Loop Position
